#ifndef BUILTINS_H
#define BUILTINS_H

enum BUILTIN_C_FUNCTIONS {
  BUILTIN_SYSTEM_CREATE_OBJECT = 0,
  BUILTIN_SYSTEM_GET_OBJECT_MEMBER = 1,
  BUILTIN_SYSTEM_SET_OBJECT_MEMBER = 2,

  BUILTIN_SYSTEM_C_EXIT = 64,
  BUILTIN_SYSTEM_C_FMOD = 65,
  BUILTIN_SYSTEM_C_STRLEN = 66,

  BUILTIN_SYSTEM_C_FOPEN = 67,
  BUILTIN_SYSTEM_C_FCLOSE = 68,
  BUILTIN_SYSTEM_C_FREAD = 69,
  BUILTIN_SYSTEM_C_FWRITE = 70,
  BUILTIN_SYSTEM_C_FSEEK = 71
};

#endif
